[project]
name = "dragonfly-bot"
version = "3.0.0"
dynamic = ["dependencies"]

[project.urls]
repository = "https://github.com/letsbuilda/dragonfly-bot"
documentation = "https://docs.letsbuilda.dev/dragonfly-bot/"

[project.optional-dependencies]
dev = [
    "pip-tools",
    "pre-commit",
    "black",
    "isort",
    "ruff",
]
tests = [
    "pytest",
]
docs = [
    "sphinx",
    "furo",
    "sphinx-autoapi",
    "toml",
    "releases",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic.dependencies]
file = ["requirements.txt"]

[tool.isort]
profile = "black"

[tool.black]
target-version = ["py310"]
line-length = 120

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
addopts = "tests -r a -v --doctest-modules src"
